function fit_bodger
% Code for manually fitting XPS curves for XSW analysis
% Requires:
% XPS_forced.m
clear; clc; close all
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Load data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% filenames = []; pathname = [];
[filenames,pathname] = uigetfile({'*.nxs','nexus'},'MultiSelect','on');
[data_square,i0,hv,nixswr,angles,energy,polar] = i09_export_XSW(filenames,pathname);
% data_square = [detector angles (angles),photon energy (hv), binding energy (energy)]

% Averaging if more than one data set loaded
data_square4d = data_square;
if ndims(data_square) == 4
    hv = hv(1:size(data_square,2));
    nixswr = nixswr(1:size(data_square,2));
    data_square = mean(data_square4d,4);    
end

% Plots all data and compares to average
figure(3)
set(gcf,'units','normalized','outerposition',[0 0.04 1 0.96])
for n = 1:size(data_square4d,4) + 1
    if n <= size(data_square4d,4)
        for nn = 1:length(hv)
            data_export(nn,:) = squeeze(sum(data_square4d(:,nn,:,n),1))';
        end
        data = mean(data_export,1);
    else
        for nn = 1:length(hv)
            data_export(nn,:) = squeeze(sum(data_square(:,nn,:)))';
        end
        data = mean(data_export,1);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% c_data  =[600, 1e6, 0.0005, 1;    -2, 2e5, -2e5, 1;    0, 0.4, 1e-5, 1;    0.05, 0.9, 0.00, 1;    0.4, 1.5, 0.1, 1;...
%     318, 1e7, 0, 1;    286, 287, 284, 0;    0.45, 0.46, 0.44, 1;...
%     250, 1e6, 1e-8, 0;    -1, -0.5, -3, 0;    0.49, 8, 0.2, 0;...    
%     70, 1000, 0, 0;    0.50, 0.7, 0.4, 0;    0.75, 1, 0.2, 0;...
%     50, 1e6, 0, 0;    3.6, 6, 3, 0;    3, 8, 0.1, 0;...
%     700, 1e6, 0, 0;    11.3, 11.5, 11.1, 0;    5., 9, 0.1, 0;...
%     500,  1e6, 0, 0;    9, 10, 8, 0;    0.6, 0.9, 0.1, 0;...
%     0.4, 0.5, 0.3, 0;   0, 1, 0.000000005, 0;    0, 2 ,-2, 0];

c_data = dlmread('c_data_bodge.txt');
no_peaks = 1;

hv = mean(hv);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

save_c_data = uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.91,0.935,0.08,0.05],...
    'string','Save',...
    'fontsize',18,...
    'callback',@save_func);

    function save_func(source,event)
        dlmwrite('c_data_bodge.txt',c_data)
    end

[c_out,titles,err] = XPS_forced(data,hv,energy,c_data,no_peaks);
c_table = uitable('Data',[cellstr(titles);num2cell(round(c_out*100)/100)]',...
    'columnname',{'Title','c_out'},...
    'rowname',{},...
    'units','normalized',...
    'position',[0.91,0.295,0.08,0.63],...
    'fontsize',12,...
    'columnEditable',[false,false]);

    function XPS_run
        [c_out,titles,err] = XPS_forced(data,hv,energy,c_data,no_peaks);
        set(c_table,'Data',[cellstr(titles);num2cell(round(c_out*100)/100)]')
        c_data(:,1) = c_out';
    end


peak_no_select = uicontrol('Style','popupmenu',...
    'units','normalized',...
    'position',[0.03,0.9,0.1,0.05],...
    'string',[1;2;3;4;5;6],...
    'Value',no_peaks,...
    'fontsize',16,...
    'Callback',@peak_no_listen);

peak_no_text = uicontrol('style','text',...
    'units','normalized',...
    'position',[0.03,0.95,0.1,0.03],...
    'string', sprintf('Peaks = %i',peak_no_select.Value),...
    'fontsize',16);

    function peak_no_listen(source,event)
        no_peaks = peak_no_select.Value;
        set(peak_no_text,'string', sprintf('Peaks = %i',peak_no_select.Value))
        
        for np = 1:no_peaks
            set(UIpanels{np},'Visible','on')
            c_data(np*3+3,4) = 1;
            c_data(np*3+5,4) = 1;
        end
        
        for np = no_peaks+1:size(UIpanels,2)
            set(UIpanels{np},'Visible','off')
            c_data(np*3+3,4) = 0;
            c_data(np*3+5,4) = 0;
        end
        XPS_run 
    end
%%% Width 
width_panel = uipanel('Title','Width','FontSize',16,...
    'units','normalized',...
    'Position',[0.03, 0.81, 0.35, 0.1]);
    
    width_max_set = uicontrol('Style','Edit',...
        'parent',width_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.05,0.2,0.5],...
        'String',0.9,...
        'Fontsize',16,...
        'Callback',@width_slide_max_func);
    uicontrol('Style','text',...
        'parent',width_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.6,0.2,0.5],...
        'String','Max',...
        'Fontsize',16);
    width_min_set = uicontrol('Style','Edit',...
        'parent',width_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.05,0.2,0.5],...
        'String',0.2,...
        'Fontsize',16,...
        'Callback',@width_slide_min_func);
    uicontrol('Style','text',...
        'parent',width_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.6,0.2,0.5],...
        'String','Min',...
        'Fontsize',16);
    
    width_slide = uicontrol('Style','Slider',...
        'parent',width_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.05,0.5,0.5],...
        'Value', c_data(8,1),...
        'Max', 0.9,...
        'Min', 0.2,...
        'sliderstep', [0.01,0.1],...
        'callback',@width_slide_func);
    
    width_slide_text =  uicontrol('Style','text',...
        'parent',width_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.6,0.3,0.4],...
        'String', sprintf('Width = %.3f',width_slide.Value),...
        'fontsize',16);
    
    
    function width_slide_func(source,event)
        set(width_slide_text,'String',sprintf('Width = %.3f',width_slide.Value))
        for np = 1:6
            c_data(np*3+5,1) = width_slide.Value;
            c_data(np*3+5,2 )= width_slide.Value + 0.1;
            c_data(np*3+5,3) = width_slide.Value - 0.1;
        end
        c_data(8,1) = width_slide.Value;
        XPS_run
    end
    
    
    function width_slide_max_func(source,event)
        if str2double(width_max_set.String) > str2double(width_min_set.String)
            if str2double(width_max_set.String) < width_slide.Value
                set(width_slide,'Value',str2double(width_max_set.String))
                set(width_slide_text,'String',sprintf('Width = %.3f',width_slide.Value))
                for np = 1:no_peaks
                    c_data(np*3+5,1) = width_slide.Value;
                end
            end
            set(width_slide,'Max',str2double(width_max_set.String))
        else
            warning('Value must be between upper and lower bounds')
        end
        for np = 1:6
            c_data(np*3+5,2) = width_slide.Value+0.1;
        end
        XPS_run
    end
    function width_slide_min_func(source,event)
        if str2double(width_max_set.String) > str2double(width_min_set.String)
            if str2double(width_min_set.String) > width_slide.Value
                set(width_slide,'Value',str2double(width_min_set.String))
                set(width_slide_text,'String',sprintf('Width = %.3f',width_slide.Value))
                for np = 1:no_peaks
                    c_data(np*3+5,1) = width_slide.Value;
                end
            end
            set(width_slide,'Min',str2double(width_min_set.String))
        else
            warning('Value must be between upper and lower bounds')
        end
        for np = 1:6
            c_data(np*3+5,3) = width_slide.Value-0.1;
        end
        XPS_run
    end
    

%%% Peak 1

peak1_panel = uipanel('Title','Peak 1','FontSize',16,...
    'units','normalized',...
    'Position',[0.03, 0.68, 0.35, 0.1]);
    
    peak1_max_set = uicontrol('Style','Edit',...
        'parent',peak1_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.05,0.2,0.5],...
        'String',c_data(7,2),...
        'Fontsize',16,...
        'Callback',@peak1_slide_max_func);
    uicontrol('Style','text',...
        'parent',peak1_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.6,0.2,0.5],...
        'String','Max',...
        'Fontsize',16);
    peak1_min_set = uicontrol('Style','Edit',...
        'parent',peak1_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.05,0.2,0.5],...
        'String',c_data(7,3),...
        'Fontsize',16,...
        'Callback',@peak1_slide_min_func);
    uicontrol('Style','text',...
        'parent',peak1_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.6,0.2,0.5],...
        'String','Min',...
        'Fontsize',16);
    
    peak1_slide = uicontrol('Style','Slider',...
        'parent',peak1_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.05,0.5,0.5],...
        'Value', c_data(7,1),...
        'Max', c_data(7,2),...
        'Min', c_data(7,3),...
        'sliderstep', [0.01,0.1],...
        'callback',@peak1_slide_func);
    peak1_slide_text =  uicontrol('Style','text',...
        'parent',peak1_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.6,0.3,0.4],...
        'String', sprintf('Energy 1 = %.2f',peak1_slide.Value),...
        'fontsize',16);
    
    
    function peak1_slide_func(source,event)
        c_data(7,1) = peak1_slide.Value;
        set(peak1_slide_text,'String',sprintf('Energy 1 = %.2f',peak1_slide.Value))
        XPS_run
    end
    
    
    function peak1_slide_max_func(source,event)
        c_data(7,2) = str2double(peak1_max_set.String);
        if c_data(7,2) > c_data(7,3)
            if c_data(7,2) < peak1_slide.Value
                set(peak1_slide,'Value',c_data(7,2))
                set(peak1_slide_text,'String',sprintf('Energy 1 = %.2f',peak1_slide.Value))
            end
            set(peak1_slide,'Max',c_data(7,2))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run
    end
    function peak1_slide_min_func(source,event)
        c_data(7,3) = str2double(peak1_min_set.String);
        if c_data(7,2) > c_data(7,3)
            if c_data(7,3) > peak1_slide.Value
                set(peak1_slide,'Value',c_data(7,3))
                set(peak1_slide_text,'String',sprintf('Energy 1 = %.2f',peak1_slide.Value))
            end
            set(peak1_slide,'Min',c_data(7,3))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run
    end

%%% Peak 2

peak2_panel = uipanel('Title','Peak 2','FontSize',16,...
    'units','normalized',...
    'Position',[0.03, 0.55, 0.35, 0.1],...
    'Visible','off');
    
    peak2_max_set = uicontrol('Style','Edit',...
        'parent',peak2_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.05,0.2,0.5],...
        'String',c_data(10,2),...
        'Fontsize',16,...
        'Callback',@peak2_slide_max_func);
    uicontrol('Style','text',...
        'parent',peak2_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.6,0.2,0.5],...
        'String','Max',...
        'Fontsize',16);
    peak2_min_set = uicontrol('Style','Edit',...
        'parent',peak2_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.05,0.2,0.5],...
        'String',c_data(10,3),...
        'Fontsize',16,...
        'Callback',@peak2_slide_min_func);
    uicontrol('Style','text',...
        'parent',peak2_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.6,0.2,0.5],...
        'String','Min',...
        'Fontsize',16);
    
    peak2_slide = uicontrol('Style','Slider',...
        'parent',peak2_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.05,0.5,0.5],...
        'Value', c_data(10,1),...
        'Max', c_data(10,2),...
        'Min', c_data(10,3),...
        'sliderstep', [0.01,0.1],...
        'callback',@peak2_slide_func);
    peak2_slide_text =  uicontrol('Style','text',...
        'parent',peak2_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.6,0.3,0.4],...
        'String', sprintf('Energy 1 = %.2f',peak2_slide.Value),...
        'fontsize',16);
    
    
    function peak2_slide_func(source,event)
        c_data(10,1) = peak2_slide.Value;
        set(peak2_slide_text,'String',sprintf('Energy 2 = %.2f',peak2_slide.Value))
        XPS_run
    end
    
    
    function peak2_slide_max_func(source,event)
        c_data(10,2) = str2double(peak2_max_set.String);
        if c_data(10,2) > c_data(10,3)
            if c_data(10,2) < peak2_slide.Value
                set(peak2_slide,'Value',c_data(10,2))
                set(peak2_slide_text,'String',sprintf('Energy 2 = %.2f',peak2_slide.Value))
            end
            set(peak2_slide,'Max',c_data(10,2))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run
    end
    function peak2_slide_min_func(source,event)
        c_data(10,3) = str2double(peak2_min_set.String);
        if c_data(10,2) > c_data(10,3)
            if c_data(10,3) > peak2_slide.Value
                set(peak2_slide,'Value',c_data(10,3))
                set(peak2_slide_text,'String',sprintf('Energy 2 = %.2f',peak2_slide.Value))
            end
            set(peak2_slide,'Min',c_data(10,3))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run
    end

%%% Peak 3

peak3_panel = uipanel('Title','Peak 3','FontSize',16,...
    'units','normalized',...
    'Position',[0.03, 0.42, 0.35, 0.1],...
    'Visible','off');
    
    peak3_max_set = uicontrol('Style','Edit',...
        'parent',peak3_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.05,0.2,0.5],...
        'String',c_data(13,2),...
        'Fontsize',16,...
        'Callback',@peak3_slide_max_func);
    uicontrol('Style','text',...
        'parent',peak3_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.6,0.2,0.5],...
        'String','Max',...
        'Fontsize',16);
    peak3_min_set = uicontrol('Style','Edit',...
        'parent',peak3_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.05,0.2,0.5],...
        'String',c_data(13,3),...
        'Fontsize',16,...
        'Callback',@peak3_slide_min_func);
    uicontrol('Style','text',...
        'parent',peak3_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.6,0.2,0.5],...
        'String','Min',...
        'Fontsize',16);
    
    peak3_slide = uicontrol('Style','Slider',...
        'parent',peak3_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.05,0.5,0.5],...
        'Value', c_data(13,1),...
        'Max', c_data(13,2),...
        'Min', c_data(13,3),...
        'sliderstep', [0.01,0.1],...
        'callback',@peak3_slide_func);
    peak3_slide_text =  uicontrol('Style','text',...
        'parent',peak3_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.6,0.3,0.4],...
        'String', sprintf('Energy 3 = %.2f',peak3_slide.Value),...
        'fontsize',16);
    
    
    function peak3_slide_func(source,event)
        c_data(13,1) = peak3_slide.Value;
        set(peak3_slide_text,'String',sprintf('Energy 3 = %.2f',peak3_slide.Value))
        XPS_run 
    end
    
    
    function peak3_slide_max_func(source,event)
        c_data(13,2) = str2double(peak3_max_set.String);
        if c_data(13,2) > c_data(13,3)
            if c_data(13,2) < peak3_slide.Value
                set(peak3_slide,'Value',c_data(13,2))
                set(peak3_slide_text,'String',sprintf('Energy 3 = %.2f',peak3_slide.Value))
            end
            set(peak3_slide,'Max',c_data(13,2))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end
    function peak3_slide_min_func(source,event)
        c_data(13,3) = str2double(peak3_min_set.String);
        if c_data(13,2) > c_data(13,3)
            if c_data(13,3) > peak3_slide.Value
                set(peak3_slide,'Value',c_data(13,3))
                set(peak3_slide_text,'String',sprintf('Energy 3 = %.2f',peak3_slide.Value))
            end
            set(peak3_slide,'Min',c_data(13,3))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end



%%% Peak 4

peak4_panel = uipanel('Title','Peak 4','FontSize',16,...
    'units','normalized',...
    'Position',[0.03, 0.29, 0.35, 0.1],...
    'Visible','off');
    
    peak4_max_set = uicontrol('Style','Edit',...
        'parent',peak4_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.05,0.2,0.5],...
        'String',c_data(16,2),...
        'Fontsize',16,...
        'Callback',@peak4_slide_max_func);
    uicontrol('Style','text',...
        'parent',peak4_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.6,0.2,0.5],...
        'String','Max',...
        'Fontsize',16);
    peak4_min_set = uicontrol('Style','Edit',...
        'parent',peak4_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.05,0.2,0.5],...
        'String',c_data(16,3),...
        'Fontsize',16,...
        'Callback',@peak4_slide_min_func);
    uicontrol('Style','text',...
        'parent',peak4_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.6,0.2,0.5],...
        'String','Min',...
        'Fontsize',16);
    
    peak4_slide = uicontrol('Style','Slider',...
        'parent',peak4_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.05,0.5,0.5],...
        'Value', c_data(16,1),...
        'Max', c_data(16,2),...
        'Min', c_data(16,3),...
        'sliderstep', [0.01,0.1],...
        'callback',@peak4_slide_func);
    peak4_slide_text =  uicontrol('Style','text',...
        'parent',peak4_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.6,0.3,0.4],...
        'String', sprintf('Energy 4 = %.2f',peak4_slide.Value),...
        'fontsize',16);
    
    
    function peak4_slide_func(source,event)
        c_data(16,1) = peak4_slide.Value;
        set(peak4_slide_text,'String',sprintf('Energy 4 = %.2f',peak4_slide.Value))
        XPS_run 
    end
    
    
    function peak4_slide_max_func(source,event)
        c_data(16,2) = str2double(peak4_max_set.String);
        if c_data(16,2) > c_data(16,3)
            if c_data(16,2) < peak4_slide.Value
                set(peak4_slide,'Value',c_data(16,2))
                set(peak4_slide_text,'String',sprintf('Energy 4 = %.2f',peak4_slide.Value))
            end
            set(peak4_slide,'Max',c_data(16,2))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end
    function peak4_slide_min_func(source,event)
        c_data(16,3) = str2double(peak4_min_set.String);
        if c_data(16,2) > c_data(16,3)
            if c_data(16,3) > peak4_slide.Value
                set(peak4_slide,'Value',c_data(16,3))
                set(peak4_slide_text,'String',sprintf('Energy 4 = %.2f',peak4_slide.Value))
            end
            set(peak4_slide,'Min',c_data(16,3))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end

%%% Peak 5

peak5_panel = uipanel('Title','Peak 5','FontSize',16,...
    'units','normalized',...
    'Position',[0.03, 0.16, 0.35, 0.1],...
    'Visible','off');
    
    peak5_max_set = uicontrol('Style','Edit',...
        'parent',peak5_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.05,0.2,0.5],...
        'String',c_data(19,2),...
        'Fontsize',16,...
        'Callback',@peak5_slide_max_func);
    uicontrol('Style','text',...
        'parent',peak5_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.6,0.2,0.5],...
        'String','Max',...
        'Fontsize',16);
    peak5_min_set = uicontrol('Style','Edit',...
        'parent',peak5_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.05,0.2,0.5],...
        'String',c_data(19,3),...
        'Fontsize',16,...
        'Callback',@peak5_slide_min_func);
    uicontrol('Style','text',...
        'parent',peak5_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.6,0.2,0.5],...
        'String','Min',...
        'Fontsize',16);
    
    peak5_slide = uicontrol('Style','Slider',...
        'parent',peak5_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.05,0.5,0.5],...
        'Value', c_data(19,1),...
        'Max', c_data(19,2),...
        'Min', c_data(19,3),...
        'sliderstep', [0.01,0.1],...
        'callback',@peak5_slide_func);
    peak5_slide_text =  uicontrol('Style','text',...
        'parent',peak5_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.6,0.3,0.4],...
        'String', sprintf('Energy 5 = %.2f',peak5_slide.Value),...
        'fontsize',16);
    
    
    function peak5_slide_func(source,event)
        c_data(19,1) = peak5_slide.Value;
        set(peak5_slide_text,'String',sprintf('Energy 5 = %.2f',peak5_slide.Value))
        XPS_run 
    end
    
    
    function peak5_slide_max_func(source,event)
        c_data(19,2) = str2double(peak5_max_set.String);
        if c_data(19,2) > c_data(19,3)
            if c_data(19,2) < peak5_slide.Value
                set(peak5_slide,'Value',c_data(19,2))
                set(peak5_slide_text,'String',sprintf('Energy 5 = %.2f',peak5_slide.Value))
            end
            set(peak5_slide,'Max',c_data(19,2))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end
    function peak5_slide_min_func(source,event)
        c_data(19,3) = str2double(peak5_min_set.String);
        if c_data(19,2) > c_data(19,3)
            if c_data(19,3) > peak5_slide.Value
                set(peak5_slide,'Value',c_data(19,3))
                set(peak5_slide_text,'String',sprintf('Energy 5 = %.2f',peak5_slide.Value))
            end
            set(peak5_slide,'Min',c_data(19,3))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end

%%% Peak 6

peak6_panel = uipanel('Title','Peak 6','FontSize',16,...
    'units','normalized',...
    'Position',[0.03, 0.03, 0.35, 0.1],...
    'Visible','off');
    
    peak6_max_set = uicontrol('Style','Edit',...
        'parent',peak6_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.05,0.2,0.5],...
        'String',c_data(22,2),...
        'Fontsize',16,...
        'Callback',@peak6_slide_max_func);
    uicontrol('Style','text',...
        'parent',peak6_panel,...
        'Units','Normalized',...
        'Position',[0.58,0.6,0.2,0.5],...
        'String','Max',...
        'Fontsize',16);
    peak6_min_set = uicontrol('Style','Edit',...
        'parent',peak6_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.05,0.2,0.5],...
        'String',c_data(22,3),...
        'Fontsize',16,...
        'Callback',@peak6_slide_min_func);
    uicontrol('Style','text',...
        'parent',peak6_panel,...
        'Units','Normalized',...
        'Position',[0.8,0.6,0.2,0.5],...
        'String','Min',...
        'Fontsize',16);
    
    peak6_slide = uicontrol('Style','Slider',...
        'parent',peak6_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.05,0.5,0.5],...
        'Value', c_data(22,1),...
        'Max', c_data(22,2),...
        'Min', c_data(22,3),...
        'sliderstep', [0.01,0.1],...
        'callback',@peak6_slide_func);
    peak6_slide_text =  uicontrol('Style','text',...
        'parent',peak6_panel,...
        'Units','Normalized',...
        'Position',[0.05,0.6,0.3,0.4],...
        'String', sprintf('Energy 6 = %.2f',peak6_slide.Value),...
        'fontsize',16);
    
    
    function peak6_slide_func(source,event)
        c_data(22,1) = peak6_slide.Value;
        set(peak6_slide_text,'String',sprintf('Energy 6 = %.2f',peak6_slide.Value))
        XPS_run 
    end
    
    
    function peak6_slide_max_func(source,event)
        c_data(22,2) = str2double(peak6_max_set.String);
        if c_data(22,2) > c_data(22,3)
            if c_data(22,2) < peak6_slide.Value
                set(peak6_slide,'Value',c_data(22,2))
                set(peak6_slide_text,'String',sprintf('Energy 6 = %.2f',peak6_slide.Value))
            end
            set(peak6_slide,'Max',c_data(22,2))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end
    function peak6_slide_min_func(source,event)
        c_data(22,3) = str2double(peak6_min_set.String);
        if c_data(22,2) > c_data(22,3)
            if c_data(22,3) > peak6_slide.Value
                set(peak6_slide,'Value',c_data(22,3))
                set(peak6_slide_text,'String',sprintf('Energy 6 = %.2f',peak6_slide.Value))
            end
            set(peak6_slide,'Min',c_data(22,3))
        else
            warning('Value must be between upper and lower bounds')
        end
        XPS_run 
    end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

UIpanels = {peak1_panel,peak2_panel,peak3_panel,peak4_panel,peak5_panel,peak6_panel};

end

