function [c_out,titles,err_1,err_2] = fit_bodge(data_square,hv,energy)
close all
f1 = figure(3);
set(f1,'units','normalized')
energy1         = [285,  288, 284,    1];
width1          = [1    3     0.0    1];
    
energy2         = [-1,   -0.5,  -1.5   1] + energy1;
width2          = [0.30933    3     0.0    1];

ener1 = energy1(1);
wid1 = width1(1);
ener2 = energy2(1);
wid2 = width2(1);

[c_out,titles,err_1,err_2] = XPS_C1s_DITP_forced(data_square,hv,energy,ener1,wid1,ener2,wid2);
%% Energy1 controls
ener1_slider = uicontrol('Style','Slider',...
                        'Units','Normalized',...
                        'Position',[0.6,0.8,0.2,0.05],...
                        'Value', energy1(1),...
                        'Max', energy1(2),...
                        'Min', energy1(3),...
                        'sliderstep', [0.01,0.1],...
                        'callback',@ener1_check...
                        );
ener1_text = uicontrol('Style','text',...
                        'Units','Normalized',...
                        'Position',[0.6,0.85,0.2,0.05],...
                        'String', ['energy1 = ',num2str(ener1_slider.Value)]...
                        );
                    
function ener1_check(source,event)
        ener1 = source.Value;
        % For R2014a and earlier:
        % val = 51 - get(source,'Value');
        set(ener1_text,'String', ['energy1 = ',num2str(ener1)])
        [c_out,titles,err_1,err_2] = XPS_C1s_DITP_forced(data_square,hv,energy,ener1,wid1,ener2,wid2);
end
%% Width1 controls
width1_slider = uicontrol('Style','Slider',...
                        'Units','Normalized',...
                        'Position',[0.6,0.7,0.2,0.05],...
                        'Value', width1(1),...
                        'Max', width1(2),...
                        'Min', width1(3),...
                        'sliderstep', [0.01,0.1],...
                        'callback',@width1_check...
                        );
width1_text = uicontrol('Style','text',...
                        'Units','Normalized',...
                        'Position',[0.6,0.75,0.2,0.05],...
                        'String', ['width1 = ',num2str(width1_slider.Value)]...
                        );
                    
function width1_check(source,event)
        wid1 = source.Value;
        % For R2014a and earlier:
        % val = 51 - get(source,'Value');
        set(width1_text,'String', ['width1 = ',num2str(wid1)])
        [c_out,titles,err_1,err_2] = XPS_C1s_DITP_forced(data_square,hv,energy,ener1,wid1,ener2,wid2);
end

%% Energy1 controls
ener2_slider = uicontrol('Style','Slider',...
                        'Units','Normalized',...
                        'Position',[0.6,0.6,0.2,0.05],...
                        'Value', energy2(1),...
                        'Max', energy2(2),...
                        'Min', energy2(3),...
                        'sliderstep', [0.01,0.1],...
                        'callback',@ener2_check...
                        );
ener2_text = uicontrol('Style','text',...
                        'Units','Normalized',...
                        'Position',[0.6,0.65,0.2,0.05],...
                        'String', ['energy2 = ',num2str(ener2_slider.Value)]...
                        );
                    
function ener2_check(source,event)
        ener2 = source.Value;
        % For R2014a and earlier:
        % val = 51 - get(source,'Value');
        set(ener2_text,'String', ['energy2 = ',num2str(ener2)])
        [c_out,titles,err_1,err_2] = XPS_C1s_DITP_forced(data_square,hv,energy,ener1,wid1,ener2,wid2);
end
%% Width1 controls
width2_slider = uicontrol('Style','Slider',...
                        'Units','Normalized',...
                        'Position',[0.6,0.5,0.2,0.05],...
                        'Value', width2(1),...
                        'Max', width2(2),...
                        'Min', width2(3),...
                        'sliderstep', [0.01,0.1],...
                        'callback',@width2_check...
                        );
width2_text = uicontrol('Style','text',...
                        'Units','Normalized',...
                        'Position',[0.6,0.55,0.2,0.05],...
                        'String', ['width2 = ',num2str(width2_slider.Value)]...
                        );
                    
function width2_check(source,event)
        wid2 = source.Value;
        % For R2014a and earlier:
        % val = 51 - get(source,'Value');
        set(width2_text,'String', ['width2 = ',num2str(wid2)])
        [c_out,titles,err_1,err_2] = XPS_C1s_DITP_forced(data_square,hv,energy,ener1,wid1,ener2,wid2);
end

%% Reset
Reset = uicontrol('Style', 'pushbutton',...
                    'Units','Normalized',...
                    'Position',[0.65,0.35,0.1,0.1],...
                    'String', 'Reset Values',...
                    'callback',@reset_func...
                    );
function reset_func(source,event)
    ener1 = ener1_slider.Value;
    wid1 = width1_slider.Value;
    ener2 = ener2_slider.Value;
    wid2 = width2_slider.Value;
    
    fprintf(['ener1 = %f \n',...
            'wid2  = %f \n',...
            'ener2 = %f (%f) \n',...
            'wid2  = %f \n'],ener1,wid1,ener2,ener2-ener1,wid2)
    [c_out,titles,err_1,err_2] = fit_bodge(data_square,hv,energy);
    
end
end